# Generated by Django 5.2.1 on 2025-05-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vpn', '0002_plan_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='plan',
            new_name='user_plan',
        ),
    ]
