# Generated by Django 5.2.1 on 2025-05-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vpn', '0003_rename_plan_purchase_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
