# Generated by Django 5.2.1 on 2025-05-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vpn', '0004_alter_tguser_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
