# Generated by Django 5.2.1 on 2025-05-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vpn', '0005_tguser_is_trial_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
