# Generated by Django 5.2.1 on 2025-05-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vpn', '0006_purchase_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_devices',
            field=models.IntegerField(default=1),
        ),
    ]
